# Generated by Django 4.0.5 on 2022-06-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plot_dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendas', models.IntegerField()),
                ('clientes', models.IntegerField()),
                ('tickets', models.IntegerField()),
            ],
        ),
    ]
