# Generated by Django 4.0.5 on 2022-06-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot_dados', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databaseteste',
            options={'managed': False},
        ),
    ]
